### ISSUE TITLE
Provide option to exclude the default view mode

### ISSUE THREAD

**Issue by MrPaulDriver** [adaptdk/er_viewmode#6]
Very cool module:-)

Please include the default view mode in the list of 'enabled view modes' so that it can be excluded if not checked.

EDIT.
I ask this because very often the default view mode is that of the full page content and this is often not suitable for simple a simple display.

**Comment by lucasconstantino** [comment]
Hi there. Just for your information:

``` php
/**
 * Implements hook_er_viewmode_get_view_modes_alter().
 */
function hook_er_viewmode_get_view_modes_alter(&$view_modes, $field, $instance) {
  unset($view_modes['full']);
}
```
